from __future__ import annotations


def complete_config() -> dict:
    return {
        "dataset_name": "test",
        "input": {
            "conditions": "conditions.parquet",
            "success_marker": "conditions.success.json",
            "expected_conditions": 4,
        },
        "output": {"root": "out", "conditions_per_shard": 2},
        "model": {
            "id": "Qwen/Qwen3-Omni-30B-A3B-Instruct",
            "path": "/models/qwen3-omni",
            "revision": "abc123",
            "processor_revision": "abc123",
            "dtype": "bfloat16",
        },
        "generation": {
            "sampling_profile": "test",
            "do_sample": True,
            "temperature": 0.7,
            "top_p": 0.8,
            "top_k": 20,
            "repetition_penalty": 1.0,
            "max_new_tokens": 128,
            "eos_token_id": 151645,
            "stop_token_ids": [151645],
            "use_audio_in_video": True,
            "system_prompt": None,
            "master_seed": 7,
            "max_model_tokens": 4096,
            "video_fps": 2.0,
            "video_min_frames": 4,
            "video_max_frames": 768,
            "image_max_pixels": 6422528,
        },
        "runtime": {
            "backend": "vllm_ascend",
            "hardware": "a2",
            "tensor_parallel_size": 4,
            "enable_expert_parallel": True,
            "distributed_executor_backend": "mp",
            "gpu_memory_utilization": 0.9,
            "max_num_seqs": 16,
            "max_num_batched_tokens": 8192,
            "limit_mm_per_prompt": {"image": 8, "video": 1, "audio": 8},
            "enforce_eager": False,
        },
        "vllm_batch_size": {
            "text": 8,
            "image": 2,
            "multi_image": 1,
            "audio": 2,
            "video": 1,
            "other": 1,
        },
        "hidden_states": {
            "backend": "vllm_ascend",
            "output_root": "hidden",
            "scratch_root": "hidden/.connector",
            "layer_ids": [1, 12, 24, 36, 47],
            "num_target_layers": 48,
            "hidden_size": 2048,
            "dtype": "bfloat16",
            "require_final_normalized_hidden": True,
            "final_norm_weight_key": "thinker.model.norm.weight",
            "final_norm_epsilon": 1.0e-6,
            "max_shard_bytes": 1048576,
            "batch_size": {
                "text": 2,
                "image": 1,
                "multi_image": 1,
                "audio": 1,
                "video": 1,
                "other": 1,
            },
        },
    }
