#!/usr/bin/env python3
from __future__ import annotations

import argparse
import hashlib
import importlib.metadata
import json
from pathlib import Path
import sys
from typing import Any, Iterable

import torch


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from glm53_w8.contracts import TARGET_CONTRACT  # noqa: E402
from glm53_w8.hidden_cache import HiddenShardWriter  # noqa: E402
from glm53_w8.target_io import SCHEMA as TARGET_IO_SCHEMA  # noqa: E402
from glm53_w8.vllm_hidden import (  # noqa: E402
    build_engine_kwargs,
    cleanup_connector_artifact,
    load_connector_tensors,
    load_final_normalizer,
    native_connector_loader,
    trajectory_tokens,
)


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        while chunk := handle.read(8 << 20):
            digest.update(chunk)
    return digest.hexdigest()


def _records(path: Path) -> Iterable[tuple[int, dict[str, Any]]]:
    with path.open(encoding="utf-8") as handle:
        for index, line in enumerate(handle):
            if line.strip():
                value = json.loads(line)
                if not isinstance(value, dict):
                    raise ValueError(f"trajectory line {index + 1} is not an object")
                yield index, value


def _version(name: str) -> str:
    try:
        return importlib.metadata.version(name)
    except importlib.metadata.PackageNotFoundError:
        return "unknown"


def _scratch_path(root: Path, sample_id: str) -> Path:
    """Use an opaque filename so arbitrary dataset IDs cannot escape scratch_root."""

    digest = hashlib.sha256(sample_id.encode("utf-8")).hexdigest()
    return root / f"{digest}.safetensors"


def _validate_identity(
    trajectory_path: Path, target_io_dir: Path, model_path: Path
) -> tuple[dict[str, Any], dict[str, Any]]:
    io = json.loads((target_io_dir / "manifest.json").read_text(encoding="utf-8"))
    trajectory_manifest_path = trajectory_path.with_suffix(
        trajectory_path.suffix + ".manifest.json"
    )
    if not trajectory_manifest_path.is_file():
        raise FileNotFoundError(
            "Stage A trajectory manifest is required: " + str(trajectory_manifest_path)
        )
    trajectory = json.loads(trajectory_manifest_path.read_text(encoding="utf-8"))
    required = (
        "trajectory_sha256",
        "source_model_fingerprint",
        "tokenizer_fingerprint",
        "target_quantization",
    )
    if any(not trajectory.get(key) for key in required):
        raise ValueError("Stage A trajectory manifest is missing identity fields")
    io_required = (
        "source_model_fingerprint",
        "tokenizer_fingerprint",
        "source_model_dir",
        "weights_sha256",
    )
    if any(not io.get(key) for key in io_required):
        raise ValueError("target I/O manifest is missing identity provenance")
    if io.get("schema") != TARGET_IO_SCHEMA:
        raise ValueError("target I/O manifest schema does not match this W8 pipeline")
    if io.get("target_quantization") != "W8A8" or io.get("runtime_backend") != "vllm-ascend":
        raise ValueError("target I/O manifest is not a vLLM-Ascend W8A8 artifact")
    if trajectory.get("trajectory_sha256") != _sha256(trajectory_path):
        raise ValueError("Stage A trajectory checksum differs from its manifest")
    for key in ("source_model_fingerprint", "tokenizer_fingerprint"):
        if trajectory.get(key) != io.get(key):
            raise ValueError(f"Stage A and target I/O {key} differ")
    if trajectory.get("target_quantization") != "W8A8":
        raise ValueError("Stage A was not generated by the W8A8 target")
    if Path(str(io.get("source_model_dir", ""))).resolve() != model_path.resolve():
        raise ValueError("Stage B model path differs from target I/O source")
    return trajectory, io


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Teacher-force exact Stage-A tokens through vLLM-Ascend W8A8 GLM-5.3."
    )
    parser.add_argument("--trajectory-jsonl", type=Path, required=True)
    parser.add_argument("--model-path", type=Path, required=True)
    parser.add_argument("--target-io", type=Path, required=True)
    parser.add_argument("--output-dir", type=Path, required=True)
    parser.add_argument("--scratch-root", type=Path, required=True)
    parser.add_argument("--tp-size", type=int, default=8)
    parser.add_argument("--batch-size", type=int, default=1)
    parser.add_argument("--max-model-len", type=int, default=131072)
    parser.add_argument("--gpu-memory-utilization", type=float, default=0.90)
    parser.add_argument("--max-shard-mib", type=int, default=512)
    parser.add_argument("--max-samples", type=int)
    parser.add_argument("--final-norm-key", default="model.norm.weight")
    args = parser.parse_args()
    if (
        args.batch_size < 1
        or args.tp_size < 1
        or args.max_model_len < 1
        or args.max_shard_mib < 1
        or args.max_samples is not None
        and args.max_samples < 1
        or not 0.0 < args.gpu_memory_utilization <= 1.0
    ):
        raise ValueError("Stage-B sizes and GPU utilization must be valid positive values")
    trajectory_manifest, io = _validate_identity(
        args.trajectory_jsonl, args.target_io, args.model_path
    )
    existing_manifest = args.output_dir / "manifest.json"
    if existing_manifest.is_file():
        existing = json.loads(existing_manifest.read_text(encoding="utf-8"))
        if existing.get("status") == "frozen":
            print(f"hidden cache is already frozen: {args.output_dir}", flush=True)
            return
    provenance = {
        "target_quantization": "W8A8",
        "runtime_backend": "vllm-ascend",
        "source_model_fingerprint": io["source_model_fingerprint"],
        "tokenizer_fingerprint": io["tokenizer_fingerprint"],
        "target_io_weights_sha256": io["weights_sha256"],
        "trajectory_sha256": trajectory_manifest["trajectory_sha256"],
        "logical_layer_ids": list(TARGET_CONTRACT.layer_ids),
        "requested_layer_ids": [
            *TARGET_CONTRACT.layer_ids,
            TARGET_CONTRACT.num_hidden_layers,
        ],
        "layer_indexing": "vllm-layer-id",
        "vllm_version": _version("vllm"),
        "vllm_ascend_version": _version("vllm-ascend"),
        "torch_npu_version": _version("torch-npu"),
        "tensor_parallel_size": args.tp_size,
        "quantization_argument": "ascend",
    }
    normalizer = load_final_normalizer(
        args.model_path, weight_key=args.final_norm_key
    )
    args.scratch_root.mkdir(parents=True, exist_ok=True)
    with HiddenShardWriter(
        args.output_dir,
        hidden_size=TARGET_CONTRACT.hidden_size,
        layer_ids=TARGET_CONTRACT.layer_ids,
        provenance=provenance,
        max_shard_bytes=args.max_shard_mib << 20,
    ) as writer:
        pending: list[tuple[int, dict[str, Any], list[int], list[bool], str]] = []
        pending_ids: set[str] = set()
        for source_index, record in _records(args.trajectory_jsonl):
            ids, mask, sample_id = trajectory_tokens(record)
            if len(ids) > args.max_model_len:
                raise ValueError(
                    f"trajectory sample {sample_id!r} has {len(ids)} tokens, "
                    f"exceeding max_model_len={args.max_model_len}"
                )
            if sample_id in writer.completed_ids:
                continue
            if sample_id in pending_ids:
                raise ValueError(f"duplicate sample_id in Stage A trajectory: {sample_id}")
            pending_ids.add(sample_id)
            pending.append((source_index, record, ids, mask, sample_id))
            if args.max_samples is not None and len(pending) >= args.max_samples:
                break
        if not pending:
            writer.freeze()
            return
        from vllm import LLM, SamplingParams

        llm = LLM(
            **build_engine_kwargs(
                model_path=args.model_path,
                tensor_parallel_size=args.tp_size,
                scratch_root=args.scratch_root,
                max_model_len=args.max_model_len,
                gpu_memory_utilization=args.gpu_memory_utilization,
            )
        )
        for begin in range(0, len(pending), args.batch_size):
            batch = pending[begin : begin + args.batch_size]
            paths = [_scratch_path(args.scratch_root, sample_id) for *_, sample_id in batch]
            requests = [{"prompt_token_ids": item[2]} for item in batch]
            params = [
                SamplingParams(
                    max_tokens=1,
                    temperature=0.0,
                    extra_args={
                        "kv_transfer_params": {
                            "hidden_states_path": str(path),
                            "include_output_tokens": False,
                        }
                    },
                )
                for path in paths
            ]
            outputs = llm.generate(requests, sampling_params=params, use_tqdm=False)
            if len(outputs) != len(batch):
                raise RuntimeError("vLLM hidden extractor returned an incomplete batch")
            for item, requested_path, output in zip(batch, paths, outputs, strict=True):
                source_index, _, ids, mask, sample_id = item
                actual = Path(
                    str((output.kv_transfer_params or {}).get("hidden_states_path", ""))
                )
                if actual != requested_path:
                    raise RuntimeError("vLLM connector ignored the requested hidden path")
                try:
                    tensors = load_connector_tensors(
                        actual,
                        ids,
                        normalizer=normalizer,
                        tensor_loader=native_connector_loader,
                    )
                    writer.append(
                        sample_id=sample_id,
                        input_ids=torch.tensor(ids, dtype=torch.int64),
                        loss_mask=torch.tensor(mask, dtype=torch.bool),
                        aux_hidden_states=tensors["aux_hidden_states"],
                        target_final_hidden=tensors["target_final_hidden"],
                    )
                finally:
                    cleanup_connector_artifact(actual)
                print(f"hidden sample={source_index} id={sample_id}", flush=True)
        # A bounded debug extraction intentionally remains resumable/building.
        if args.max_samples is None:
            writer.freeze()
        else:
            writer.commit_partial()


if __name__ == "__main__":
    main()
